services:
  db:
    image: postgres:16
    container_name: nutritrack-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: nutritrack_testing
    ports:
      - "5470:5432"
    volumes:
      - nutritrack_pgdata:/var/lib/postgresql/data
      - ./backupOk.sql:/docker-entrypoint-initdb.d/backupOk.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutritrack-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=nutritrack_testing;Username=postgres;Password=1234"
    ports:
      - "8080:8080"

volumes:
  nutritrack_pgdata: